// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var ARRAY, ARRAY_PROTOTYPE, NATIVE_FUNCTION, NULL, OBJECT, STRING, isIntegery;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION, STRING = jinter.STRING;

  ARRAY_PROTOTYPE = new OBJECT(NULL);

  ARRAY_PROTOTYPE.put('toString', new NATIVE_FUNCTION(function() {
    var resultRaw;
    resultRaw = Array.prototype.toString.apply(this.data, arguments);
    return {
      "return": true,
      value: new STRING(resultRaw)
    };
  }));

  ARRAY_PROTOTYPE.put('slice', new NATIVE_FUNCTION(function() {
    var resultRaw;
    resultRaw = Array.prototype.slice.apply(this.data, arguments);
    return {
      "return": true,
      value: new ARRAY(resultRaw)
    };
  }));

  ARRAY = function(data) {
    this.data = data != null ? data : [];
    OBJECT.call(this, ARRAY_PROTOTYPE);
    this.put('prototype', ARRAY_PROTOTYPE);
  };

  ARRAY.prototype = Object.create(OBJECT.prototype);

  ARRAY.prototype.constructor = ARRAY;

  isIntegery = function(value) {
    if (isNaN(value)) {
      return;
    }
    return (parseFloat(value)) === (parseInt(value, 10));
  };

  ARRAY.prototype.get = function(key) {
    if (isIntegery(key)) {
      return this.data[key];
    } else {
      return OBJECT.prototype.get.call(this, key);
    }
  };

  ARRAY.prototype.put = function(key, value) {
    if (isIntegery(key)) {
      return this.data[key] = value;
    } else {
      return OBJECT.prototype.get.call(this, key);
    }
  };

  ARRAY.prototype.toString = function() {
    return this.data.toString();
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.ARRAY = ARRAY;

}).call(this);
