// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var BOOLEAN;

  BOOLEAN = function(value) {
    this.value = Boolean(value);
  };

  BOOLEAN.prototype.type = 'boolean';

  BOOLEAN.prototype.typeOf = 'boolean';

  BOOLEAN.prototype.toNumber = function() {
    return Number(this.value);
  };

  BOOLEAN.prototype.toBoolean = function() {
    return this.value;
  };

  BOOLEAN.prototype.toString = function() {
    return String(this.value);
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.BOOLEAN = BOOLEAN;

}).call(this);
