// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var EMPTY, Node, UNDEFINED;

  UNDEFINED = jinter.UNDEFINED;

  Node = function(parent) {
    this.parent = parent;
    this.bindings = new Map;
  };

  Node.prototype.get = function(key) {
    if (this.bindings.has(key)) {
      return this.bindings.get(key);
    } else {
      return this.parent.get(key);
    }
  };

  Node.prototype.set = function(key, value) {
    if (this.bindings.has(key)) {
      this.bindings.set(key, value);
    } else {
      this.parent.set(key, value);
    }
  };

  Node.prototype.addEntry = function() {
    return new Node(this);
  };

  Node.prototype.addBinding = function(key, value) {
    return this.bindings.set(key, value);
  };

  EMPTY = {
    get: function(key) {
      throw new Error("Could not find " + key);
    },
    addEntry: function() {
      return new Node(EMPTY);
    },
    addBinding: function() {
      return new Node(EMPTY);
    }
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.EMPTY = EMPTY;

}).call(this);
