// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var EMPTY, FUNCTION, FUNCTION_PROTOTYPE, NULL, OBJECT;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, EMPTY = jinter.EMPTY, FUNCTION_PROTOTYPE = jinter.FUNCTION_PROTOTYPE;

  FUNCTION = function(body, env, formalArguments, ownName) {
    this.body = body;
    this.env = env;
    this.formalArguments = formalArguments;
    this.ownName = ownName;
    OBJECT.call(this, FUNCTION_PROTOTYPE);
    this.put('prototype', new OBJECT(NULL));
  };

  FUNCTION.prototype = Object.create(OBJECT.prototype);

  FUNCTION.prototype.constructor = FUNCTION;

  FUNCTION.prototype.typeOf = 'function';

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.FUNCTION = FUNCTION;

}).call(this);
