// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var MAP, OBJECT;

  OBJECT = jinter.OBJECT;

  MAP = function(store) {
    this.store = store != null ? store : new Map;
    OBJECT.call(this, jinter.MAP_PROTOTYPE);
  };

  MAP.prototype = Object.create(OBJECT.prototype);

  MAP.prototype.constructor = MAP;

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.MAP = MAP;

}).call(this);
