// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NUMBER, STRING;

  STRING = jinter.STRING;

  NUMBER = function(value) {
    this.value = value;
  };

  NUMBER.prototype.add = function(that) {
    return that.addNumber(this);
  };

  NUMBER.prototype.addNumber = function(that) {
    return new NUMBER(that.toNumber() + this.toNumber());
  };

  NUMBER.prototype.addString = function(that) {
    return new STRING(that.toString() + this.toString());
  };

  NUMBER.prototype.sub = function(that) {
    return new NUMBER(this.toNumber() - that.toNumber());
  };

  NUMBER.prototype.toNumber = function() {
    return this.value;
  };

  NUMBER.prototype.toBoolean = function() {
    return Boolean(this.value);
  };

  NUMBER.prototype.toString = function() {
    return String(this.value);
  };

  NUMBER.prototype.isCallable = function() {
    return false;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.NUMBER = NUMBER;

}).call(this);
