// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var STRING;

  STRING = function(value) {
    this.value = value;
    this.type = 'string';
  };

  STRING.prototype.toNumber = function() {
    return Number(this.value);
  };

  STRING.prototype.toBoolean = function() {
    return Boolean(this.value);
  };

  STRING.prototype.toString = function() {
    return this.value;
  };

  STRING.prototype.toPrimitive = function() {
    return this;
  };

  STRING.prototype.isCallable = function() {
    return false;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.STRING = STRING;

}).call(this);
