// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var UNDEFINED;

  UNDEFINED = {};

  UNDEFINED.get = function(key) {
    throw new Error("Cannot read property " + key + " of undefined");
  };

  UNDEFINED.put = function(key, value) {
    throw new Error("Cannot set property " + key + " of undefined");
  };

  UNDEFINED.toNumber = function() {
    return NaN;
  };

  UNDEFINED.toBoolean = function() {
    return false;
  };

  UNDEFINED.toString = function() {
    return 'undefined';
  };

  UNDEFINED.isCallable = function() {
    return false;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.UNDEFINED = UNDEFINED;

}).call(this);
