// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NATIVE_FUNCTION, NULL, OBJECT, UNDEFINED, WINDOW;

  OBJECT = jinter.OBJECT, UNDEFINED = jinter.UNDEFINED, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION;

  WINDOW = new OBJECT(NULL);

  WINDOW.put('undefined', UNDEFINED);

  (function() {
    var OBJ, create;
    OBJ = new OBJECT(NULL);
    WINDOW.put('Object', OBJ);
    create = new NATIVE_FUNCTION(function(proto) {
      return {
        "return": true,
        value: new OBJECT(proto)
      };
    });
    return OBJ.put('create', create);
  })();

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.WINDOW = WINDOW;

}).call(this);
