// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var ARRAY, OBJECT, isNatural;

  OBJECT = jinter.OBJECT;

  ARRAY = function(data) {
    this.data = data != null ? data : [];
    OBJECT.call(this, jinter.ARRAY_PROTOTYPE);
  };

  ARRAY.prototype = Object.create(OBJECT.prototype);

  ARRAY.prototype.constructor = ARRAY;

  ARRAY.prototype["class"] = 'Array';

  isNatural = function(value) {
    return (!isNaN(value)) && (parseFloat(value)) === (parseInt(value, 10)) && (0 <= value);
  };

  ARRAY.prototype.get = function(key) {
    if (isNatural(key)) {
      return this.data[key];
    } else {
      return OBJECT.prototype.get.call(this, key);
    }
  };

  ARRAY.prototype.put = function(key, value) {
    if (isNatural(key)) {
      this.data[key] = value;
    } else {
      OBJECT.prototype.put.call(this, key, value);
    }
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.ARRAY = ARRAY;

}).call(this);
