// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var ARRAY, OBJECT, isIntegery;

  OBJECT = jinter.OBJECT;

  ARRAY = function(data) {
    this.data = data != null ? data : [];
    OBJECT.call(this, jinter.ARRAY_PROTOTYPE);
  };

  ARRAY.prototype = Object.create(OBJECT.prototype);

  ARRAY.prototype.constructor = ARRAY;

  isIntegery = function(value) {
    if (isNaN(value)) {
      return;
    }
    return (parseFloat(value)) === (parseInt(value, 10));
  };

  ARRAY.prototype.get = function(key) {
    if (isIntegery(key)) {
      return this.data[key];
    } else {
      return OBJECT.prototype.get.call(this, key);
    }
  };

  ARRAY.prototype.put = function(key, value) {
    if (isIntegery(key)) {
      return this.data[key] = value;
    } else {
      return OBJECT.prototype.get.call(this, key);
    }
  };

  ARRAY.prototype.toString = function() {
    return this.data.toString();
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.ARRAY = ARRAY;

}).call(this);
