// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var BOOLEAN_FUNCTION, BOOLEAN_PROTOTYPE, NATIVE_FUNCTION, NULL, OBJECT;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION;

  BOOLEAN_FUNCTION = new NATIVE_FUNCTION(function(candidate) {
    return {
      "return": true,
      value: new jinter.BOOLEAN(candidate.asBoolean())
    };
  });

  BOOLEAN_PROTOTYPE = new OBJECT(NULL);

  BOOLEAN_FUNCTION.put('prototype', BOOLEAN_PROTOTYPE);

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.BOOLEAN_PROTOTYPE = BOOLEAN_PROTOTYPE;

  window.jinter.BOOLEAN_FUNCTION = BOOLEAN_FUNCTION;

}).call(this);
