// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var EMPTY, FUNCTION_FUNCTION, FUNCTION_PROTOTYPE, NATIVE_FUNCTION, NULL, OBJECT, apply, call,
    __slice = [].slice;

  NULL = jinter.NULL, OBJECT = jinter.OBJECT, EMPTY = jinter.EMPTY, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION;

  FUNCTION_FUNCTION = new NATIVE_FUNCTION(function() {
    throw new Error('Function function not implemented');
  });

  FUNCTION_PROTOTYPE = new OBJECT(NULL);

  FUNCTION_FUNCTION.put('prototype', FUNCTION_PROTOTYPE);

  apply = new jinter.NATIVE_FUNCTION(function(thisArgument, args) {
    return jinter.callRaw(this, thisArgument, args.data, EMPTY);
  });

  FUNCTION_PROTOTYPE.put('apply', apply);

  call = new jinter.NATIVE_FUNCTION(function() {
    var args, thisArgument;
    thisArgument = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return jinter.callRaw(this, thisArgument, args, EMPTY);
  });

  FUNCTION_PROTOTYPE.put('call', call);

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.FUNCTION_PROTOTYPE = FUNCTION_PROTOTYPE;

  window.jinter.FUNCTION_FUNCTION = FUNCTION_FUNCTION;

}).call(this);
