// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NATIVE_FUNCTION, NULL, NUMBER_FUNCTION, NUMBER_PROTOTYPE, OBJECT;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION;

  NUMBER_FUNCTION = new NATIVE_FUNCTION(function(candidate) {
    return {
      "return": true,
      value: new jinter.NUMBER(candidate.asNumber())
    };
  });

  NUMBER_PROTOTYPE = new OBJECT(NULL);

  NUMBER_FUNCTION.put('prototype', NUMBER_PROTOTYPE);

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.NUMBER_PROTOTYPE = NUMBER_PROTOTYPE;

  window.jinter.NUMBER_FUNCTION = NUMBER_FUNCTION;

}).call(this);
