// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NATIVE_FUNCTION, NULL, OBJECT, OBJECT_FUNCTION, OBJECT_PROTOTYPE, STRING, create, keys, toString;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION, STRING = jinter.STRING;

  OBJECT_FUNCTION = new OBJECT(NULL);

  create = new NATIVE_FUNCTION(function(proto) {
    return {
      "return": true,
      value: new OBJECT(proto)
    };
  });

  OBJECT_FUNCTION.put('create', create);

  keys = new NATIVE_FUNCTION(function(obj) {
    var objKeys;
    objKeys = [];
    obj.map.forEach(function(value, key) {
      return objKeys.push(new STRING(key));
    });
    return {
      "return": true,
      value: new jinter.ARRAY(objKeys)
    };
  });

  OBJECT_FUNCTION.put('keys', keys);

  OBJECT_PROTOTYPE = new OBJECT(NULL);

  OBJECT_FUNCTION.put('prototype', OBJECT_PROTOTYPE);

  toString = new NATIVE_FUNCTION(function() {
    return {
      "return": true,
      value: new STRING(this["class"] != null ? "[object " + this["class"] + "]" : "[object Object]")
    };
  });

  OBJECT_PROTOTYPE.put('toString', toString);

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.OBJECT_FUNCTION = OBJECT_FUNCTION;

  window.jinter.OBJECT_PROTOTYPE = OBJECT_PROTOTYPE;

}).call(this);
