// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NATIVE_FUNCTION, NULL, OBJECT, STRING_FUNCTION, STRING_PROTOTYPE;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL, NATIVE_FUNCTION = jinter.NATIVE_FUNCTION;

  STRING_FUNCTION = new NATIVE_FUNCTION(function(candidate) {
    return {
      "return": true,
      value: new jinter.STRING(candidate.asString())
    };
  });

  STRING_PROTOTYPE = new OBJECT(NULL);

  STRING_FUNCTION.put('prototype', STRING_PROTOTYPE);

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.STRING_PROTOTYPE = STRING_PROTOTYPE;

  window.jinter.STRING_FUNCTION = STRING_FUNCTION;

}).call(this);
