// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var BOOLEAN;

  BOOLEAN = function(value) {
    this.value = Boolean(value);
  };

  BOOLEAN.prototype.type = 'boolean';

  BOOLEAN.prototype.typeOf = 'boolean';

  BOOLEAN.prototype.get = function(key) {
    return jinter.BOOLEAN_PROTOTYPE.get(key);
  };

  BOOLEAN.prototype.set = function() {
    return null;
  };

  BOOLEAN.prototype.asNumber = function() {
    return Number(this.value);
  };

  BOOLEAN.prototype.asBoolean = function() {
    return this.value;
  };

  BOOLEAN.prototype.asString = function() {
    return String(this.value);
  };

  BOOLEAN.prototype.asPrimitive = function() {
    return this;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.BOOLEAN = BOOLEAN;

}).call(this);
