// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NATIVE_FUNCTION, NULL, OBJECT;

  OBJECT = jinter.OBJECT, NULL = jinter.NULL;

  NATIVE_FUNCTION = function(fun) {
    this.fun = fun;
    OBJECT.call(this, jinter.FUNCTION_PROTOTYPE);
    this.put('prototype', new OBJECT(NULL));
  };

  NATIVE_FUNCTION.prototype = Object.create(OBJECT.prototype);

  NATIVE_FUNCTION.prototype.constructor = NATIVE_FUNCTION;

  NATIVE_FUNCTION.prototype["native"] = true;

  NATIVE_FUNCTION.prototype.typeOf = 'function';

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.NATIVE_FUNCTION = NATIVE_FUNCTION;

}).call(this);
