// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NULL;

  NULL = {};

  NULL.type = 'null';

  NULL.typeOf = 'object';

  NULL.get = function(key) {
    return null;
  };

  NULL.put = function(key, value) {
    throw new Error("Cannot set property " + key + " of null");
  };

  NULL.asNumber = function() {
    return 0;
  };

  NULL.asBoolean = function() {
    return false;
  };

  NULL.asString = function() {
    return 'null';
  };

  NULL.asPrimitive = function() {
    return NULL;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.NULL = NULL;

}).call(this);
