// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var NUMBER, STRING;

  STRING = jinter.STRING;

  NUMBER = function(value) {
    this.value = Number(value);
  };

  NUMBER.prototype.type = 'number';

  NUMBER.prototype.typeOf = 'number';

  NUMBER.prototype.asNumber = function() {
    return this.value;
  };

  NUMBER.prototype.asBoolean = function() {
    return Boolean(this.value);
  };

  NUMBER.prototype.asString = function() {
    return String(this.value);
  };

  NUMBER.prototype.asPrimitive = function() {
    return this;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.NUMBER = NUMBER;

}).call(this);
