// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var STRING;

  STRING = function(value) {
    this.value = String(value);
  };

  STRING.prototype.type = 'string';

  STRING.prototype.typeOf = 'string';

  STRING.prototype.asNumber = function() {
    return Number(this.value);
  };

  STRING.prototype.asBoolean = function() {
    return Boolean(this.value);
  };

  STRING.prototype.asString = function() {
    return this.value;
  };

  STRING.prototype.asPrimitive = function() {
    return this;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.STRING = STRING;

}).call(this);
