// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var UNDEFINED;

  UNDEFINED = {};

  UNDEFINED.type = 'undefined';

  UNDEFINED.typeOf = 'undefined';

  UNDEFINED.get = function(key) {
    throw new Error("Cannot read property " + key + " of undefined");
  };

  UNDEFINED.put = function(key, value) {
    throw new Error("Cannot set property " + key + " of undefined");
  };

  UNDEFINED.asNumber = function() {
    return NaN;
  };

  UNDEFINED.asBoolean = function() {
    return false;
  };

  UNDEFINED.asString = function() {
    return 'undefined';
  };

  UNDEFINED.asPrimitive = function() {
    return UNDEFINED;
  };

  if (window.jinter == null) {
    window.jinter = {};
  }

  window.jinter.UNDEFINED = UNDEFINED;

}).call(this);
